/// *This is an auto-generated file, you should not update its contents*
/// 
/// Voice names fetched from Microsoft API.
 
#[allow(non_camel_case_types)]
pub enum VoiceName {
    en_AU_NatashaNeural,
    en_AU_WilliamNeural,
    en_CA_ClaraNeural,
    en_CA_LiamNeural,
    en_GB_LibbyNeural,
    en_GB_AbbiNeural,
    en_GB_AlfieNeural,
    en_GB_BellaNeural,
    en_GB_ElliotNeural,
    en_GB_EthanNeural,
    en_GB_HollieNeural,
    en_GB_MaisieNeural,
    en_GB_NoahNeural,
    en_GB_OliverNeural,
    en_GB_OliviaNeural,
    en_GB_RyanNeural,
    en_GB_SoniaNeural,
    en_GB_ThomasNeural,
    en_GB_MiaNeural,
    en_HK_SamNeural,
    en_HK_YanNeural,
    en_IE_ConnorNeural,
    en_IE_EmilyNeural,
    en_IN_NeerjaNeural,
    en_IN_PrabhatNeural,
    en_KE_AsiliaNeural,
    en_KE_ChilembaNeural,
    en_NG_AbeoNeural,
    en_NG_EzinneNeural,
    en_NZ_MitchellNeural,
    en_NZ_MollyNeural,
    en_PH_JamesNeural,
    en_PH_RosaNeural,
    en_SG_LunaNeural,
    en_SG_WayneNeural,
    en_TZ_ElimuNeural,
    en_TZ_ImaniNeural,
    en_US_JennyNeural,
    en_US_JennyMultilingualNeural,
    en_US_GuyNeural,
    en_US_AmberNeural,
    en_US_AnaNeural,
    en_US_AriaNeural,
    en_US_AshleyNeural,
    en_US_BrandonNeural,
    en_US_ChristopherNeural,
    en_US_CoraNeural,
    en_US_DavisNeural,
    en_US_ElizabethNeural,
    en_US_EricNeural,
    en_US_JacobNeural,
    en_US_JaneNeural,
    en_US_JasonNeural,
    en_US_MichelleNeural,
    en_US_MonicaNeural,
    en_US_NancyNeural,
    en_US_SaraNeural,
    en_US_SteffanNeural,
    en_US_TonyNeural,
    en_US_JennyEmotionNeural,
    en_ZA_LeahNeural,
    en_ZA_LukeNeural,
    zh_CN_XiaoxiaoNeural,
    zh_CN_YunyangNeural,
    zh_CN_XiaochenNeural,
    zh_CN_XiaohanNeural,
    zh_CN_XiaomengNeural,
    zh_CN_XiaomoNeural,
    zh_CN_XiaoqiuNeural,
    zh_CN_XiaoruiNeural,
    zh_CN_XiaoshuangNeural,
    zh_CN_XiaoxuanNeural,
    zh_CN_XiaoyanNeural,
    zh_CN_XiaoyiNeural,
    zh_CN_XiaoyouNeural,
    zh_CN_XiaozhenNeural,
    zh_CN_YunfengNeural,
    zh_CN_YunhaoNeural,
    zh_CN_YunjianNeural,
    zh_CN_YunxiaNeural,
    zh_CN_YunxiNeural,
    zh_CN_YunyeNeural,
    zh_CN_YunzeNeural,
    zh_CN_henan_YundengNeural,
    zh_CN_liaoning_XiaobeiNeural,
    zh_CN_shaanxi_XiaoniNeural,
    zh_CN_shandong_YunxiangNeural,
    zh_HK_HiuMaanNeural,
    zh_HK_HiuGaaiNeural,
    zh_HK_WanLungNeural,
    zh_TW_HsiaoChenNeural,
    zh_TW_HsiaoYuNeural,
    zh_TW_YunJheNeural,
}

impl Into<String> for VoiceName {
    fn into(self) -> String {
        (match self {
            Self::en_AU_NatashaNeural => "en-AU-NatashaNeural",
            Self::en_AU_WilliamNeural => "en-AU-WilliamNeural",
            Self::en_CA_ClaraNeural => "en-CA-ClaraNeural",
            Self::en_CA_LiamNeural => "en-CA-LiamNeural",
            Self::en_GB_LibbyNeural => "en-GB-LibbyNeural",
            Self::en_GB_AbbiNeural => "en-GB-AbbiNeural",
            Self::en_GB_AlfieNeural => "en-GB-AlfieNeural",
            Self::en_GB_BellaNeural => "en-GB-BellaNeural",
            Self::en_GB_ElliotNeural => "en-GB-ElliotNeural",
            Self::en_GB_EthanNeural => "en-GB-EthanNeural",
            Self::en_GB_HollieNeural => "en-GB-HollieNeural",
            Self::en_GB_MaisieNeural => "en-GB-MaisieNeural",
            Self::en_GB_NoahNeural => "en-GB-NoahNeural",
            Self::en_GB_OliverNeural => "en-GB-OliverNeural",
            Self::en_GB_OliviaNeural => "en-GB-OliviaNeural",
            Self::en_GB_RyanNeural => "en-GB-RyanNeural",
            Self::en_GB_SoniaNeural => "en-GB-SoniaNeural",
            Self::en_GB_ThomasNeural => "en-GB-ThomasNeural",
            Self::en_GB_MiaNeural => "en-GB-MiaNeural",
            Self::en_HK_SamNeural => "en-HK-SamNeural",
            Self::en_HK_YanNeural => "en-HK-YanNeural",
            Self::en_IE_ConnorNeural => "en-IE-ConnorNeural",
            Self::en_IE_EmilyNeural => "en-IE-EmilyNeural",
            Self::en_IN_NeerjaNeural => "en-IN-NeerjaNeural",
            Self::en_IN_PrabhatNeural => "en-IN-PrabhatNeural",
            Self::en_KE_AsiliaNeural => "en-KE-AsiliaNeural",
            Self::en_KE_ChilembaNeural => "en-KE-ChilembaNeural",
            Self::en_NG_AbeoNeural => "en-NG-AbeoNeural",
            Self::en_NG_EzinneNeural => "en-NG-EzinneNeural",
            Self::en_NZ_MitchellNeural => "en-NZ-MitchellNeural",
            Self::en_NZ_MollyNeural => "en-NZ-MollyNeural",
            Self::en_PH_JamesNeural => "en-PH-JamesNeural",
            Self::en_PH_RosaNeural => "en-PH-RosaNeural",
            Self::en_SG_LunaNeural => "en-SG-LunaNeural",
            Self::en_SG_WayneNeural => "en-SG-WayneNeural",
            Self::en_TZ_ElimuNeural => "en-TZ-ElimuNeural",
            Self::en_TZ_ImaniNeural => "en-TZ-ImaniNeural",
            Self::en_US_JennyNeural => "en-US-JennyNeural",
            Self::en_US_JennyMultilingualNeural => "en-US-JennyMultilingualNeural",
            Self::en_US_GuyNeural => "en-US-GuyNeural",
            Self::en_US_AmberNeural => "en-US-AmberNeural",
            Self::en_US_AnaNeural => "en-US-AnaNeural",
            Self::en_US_AriaNeural => "en-US-AriaNeural",
            Self::en_US_AshleyNeural => "en-US-AshleyNeural",
            Self::en_US_BrandonNeural => "en-US-BrandonNeural",
            Self::en_US_ChristopherNeural => "en-US-ChristopherNeural",
            Self::en_US_CoraNeural => "en-US-CoraNeural",
            Self::en_US_DavisNeural => "en-US-DavisNeural",
            Self::en_US_ElizabethNeural => "en-US-ElizabethNeural",
            Self::en_US_EricNeural => "en-US-EricNeural",
            Self::en_US_JacobNeural => "en-US-JacobNeural",
            Self::en_US_JaneNeural => "en-US-JaneNeural",
            Self::en_US_JasonNeural => "en-US-JasonNeural",
            Self::en_US_MichelleNeural => "en-US-MichelleNeural",
            Self::en_US_MonicaNeural => "en-US-MonicaNeural",
            Self::en_US_NancyNeural => "en-US-NancyNeural",
            Self::en_US_SaraNeural => "en-US-SaraNeural",
            Self::en_US_SteffanNeural => "en-US-SteffanNeural",
            Self::en_US_TonyNeural => "en-US-TonyNeural",
            Self::en_US_JennyEmotionNeural => "en-US-JennyEmotionNeural",
            Self::en_ZA_LeahNeural => "en-ZA-LeahNeural",
            Self::en_ZA_LukeNeural => "en-ZA-LukeNeural",
            Self::zh_CN_XiaoxiaoNeural => "zh-CN-XiaoxiaoNeural",
            Self::zh_CN_YunyangNeural => "zh-CN-YunyangNeural",
            Self::zh_CN_XiaochenNeural => "zh-CN-XiaochenNeural",
            Self::zh_CN_XiaohanNeural => "zh-CN-XiaohanNeural",
            Self::zh_CN_XiaomengNeural => "zh-CN-XiaomengNeural",
            Self::zh_CN_XiaomoNeural => "zh-CN-XiaomoNeural",
            Self::zh_CN_XiaoqiuNeural => "zh-CN-XiaoqiuNeural",
            Self::zh_CN_XiaoruiNeural => "zh-CN-XiaoruiNeural",
            Self::zh_CN_XiaoshuangNeural => "zh-CN-XiaoshuangNeural",
            Self::zh_CN_XiaoxuanNeural => "zh-CN-XiaoxuanNeural",
            Self::zh_CN_XiaoyanNeural => "zh-CN-XiaoyanNeural",
            Self::zh_CN_XiaoyiNeural => "zh-CN-XiaoyiNeural",
            Self::zh_CN_XiaoyouNeural => "zh-CN-XiaoyouNeural",
            Self::zh_CN_XiaozhenNeural => "zh-CN-XiaozhenNeural",
            Self::zh_CN_YunfengNeural => "zh-CN-YunfengNeural",
            Self::zh_CN_YunhaoNeural => "zh-CN-YunhaoNeural",
            Self::zh_CN_YunjianNeural => "zh-CN-YunjianNeural",
            Self::zh_CN_YunxiaNeural => "zh-CN-YunxiaNeural",
            Self::zh_CN_YunxiNeural => "zh-CN-YunxiNeural",
            Self::zh_CN_YunyeNeural => "zh-CN-YunyeNeural",
            Self::zh_CN_YunzeNeural => "zh-CN-YunzeNeural",
            Self::zh_CN_henan_YundengNeural => "zh-CN-henan-YundengNeural",
            Self::zh_CN_liaoning_XiaobeiNeural => "zh-CN-liaoning-XiaobeiNeural",
            Self::zh_CN_shaanxi_XiaoniNeural => "zh-CN-shaanxi-XiaoniNeural",
            Self::zh_CN_shandong_YunxiangNeural => "zh-CN-shandong-YunxiangNeural",
            Self::zh_HK_HiuMaanNeural => "zh-HK-HiuMaanNeural",
            Self::zh_HK_HiuGaaiNeural => "zh-HK-HiuGaaiNeural",
            Self::zh_HK_WanLungNeural => "zh-HK-WanLungNeural",
            Self::zh_TW_HsiaoChenNeural => "zh-TW-HsiaoChenNeural",
            Self::zh_TW_HsiaoYuNeural => "zh-TW-HsiaoYuNeural",
            Self::zh_TW_YunJheNeural => "zh-TW-YunJheNeural",
        })
        .into()
    }
}
